### ISSUE TITLE
Fix face_line parser.

### ISSUE THREAD

**Issue by s3rius** [wierd-stuff-inc/rusterizer#1]
Faceline parser fails on string `f 47//1 1//1 3//1 45//1\n`. Need to fix it. I added debug to show trace, but it was not so helpful as I thought. You can find the buggy function [here](https://github.com/wierd-stuff-inc/rusterizer/blob/master/src/parser/obj_line.rs#L144-L158).

**_It's really weird._**

**Comment by Kolaer** [comment]
Ok, will look into it.
